[versions]
agp = "9.2.1"
kotlin = "2.1.0"
djiSdkV5 = "5.18.0"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
activityKtx = "1.13.0"
constraintlayout = "2.1.4"
okhttp3 = "4.12.0"
coroutines = "1.7.3"
camerax = "1.3.4"
playServicesLocation = "21.3.0"

[libraries]
dji-aircraft = { group = "com.dji", name = "dji-sdk-v5-aircraft", version.ref = "djiSdkV5" }
dji-aircraft-provided = { group = "com.dji", name = "dji-sdk-v5-aircraft-provided", version.ref = "djiSdkV5" }
dji-network-imp = { group = "com.dji", name = "dji-sdk-v5-networkImp", version.ref = "djiSdkV5" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
camerax-core     = { group = "androidx.camera", name = "camera-core",      version.ref = "camerax" }
camerax-camera2  = { group = "androidx.camera", name = "camera-camera2",   version.ref = "camerax" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax-view     = { group = "androidx.camera", name = "camera-view",       version.ref = "camerax" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

